### ISSUE TITLE
Enforce UTF8 when writing DSV

### ISSUE THREAD

**Issue by jjaderberg** [neo4j-contrib/neo4j-sproc-compiler#56]
`DsvSerializer` uses `FileWriter`[1]  which means the system default locale will determine the encoding. We discovered this when running in a Docker container where the locale was POSIX, and any non-ASCII characters used for delimiters or in Strings in proc annotations were garbled. It would be better to enforce UTF8, or make the encoding configurable if there is a use case for other encodings.

> The constructors of this class assume that the default character encoding and the default byte-buffer size are acceptable. To specify these values yourself, construct an OutputStreamWriter on a FileOutputStream.[2]

[1]: https://github.com/oss-transfer/neo4j-sproc-compiler/blob/efe893ef10e0eeab378ab4841e8595eb2fbb23cb/processor/src/main/java/net/biville/florent/sproccompiler/export/io/DsvSerializer.java#L112
[2]: https://docs.oracle.com/javase/8/docs/api/java/io/FileWriter.html

**Comment by Mats-SX** [comment]
To experience what we did, try the following:

```
File file = /* ... */;
OutputStreamWriter posix = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.US_ASCII);
posix.write("¦"); // will write a `?`
posix.close();
```

**Comment by fbiville** [comment]
Yep, rookie mistake. Thanks for spotting the issue.
Would any of you be willing to try a PR? :)

**Comment by fbiville** [comment]
The testing has sadly been more involved than it should have been, but I've got a proper test and a fix ready to be merged, feel free to review https://github.com/oss-transfer/neo4j-sproc-compiler/pull/57.

**Comment by fbiville** [comment]
I'll do a minor release once this is merged.

**Comment by Mats-SX** [comment]
@fbiville Thank you. I will try to test this sometime soon.
